import type { MedalKind } from "./contracts/habits";

export const ICON_KEYS = [
  "1st-place-medal",
  "2nd-place-medal",
  "3rd-place-medal",
  "airplane",
  "alarm-clock",
  "anatomical-heart",
  "artist-palette",
  "automobile",
  "avocado",
  "balloon",
  "banana",
  "bank",
  "bar-chart",
  "basketball",
  "bathtub",
  "beach-with-umbrella",
  "bed",
  "beer-mug",
  "bicycle",
  "bird",
  "birthday-cake",
  "books",
  "bottle-with-popping-cork",
  "bowl-with-spoon",
  "brain",
  "bread",
  "broccoli",
  "broom",
  "bubbles",
  "bullseye",
  "bus",
  "butterfly",
  "calendar",
  "camping",
  "candle",
  "carrot",
  "cat-face",
  "chart-decreasing",
  "chart-increasing",
  "cheese-wedge",
  "cherry-blossom",
  "cloud",
  "coin",
  "comet",
  "compass",
  "confetti-ball",
  "cookie",
  "credit-card",
  "crescent-moon",
  "crown",
  "crystal-ball",
  "desktop-computer",
  "dog-face",
  "dollar-banknote",
  "droplet",
  "egg",
  "envelope",
  "euro-banknote",
  "evergreen-tree",
  "fallen-leaf",
  "fire",
  "flexed-biceps",
  "footprints",
  "fork-and-knife-with-plate",
  "four-leaf-clover",
  "fuel-pump",
  "gauge",
  "gem-stone",
  "glass-of-milk",
  "glowing-star",
  "grapes",
  "green-apple",
  "green-salad",
  "guitar",
  "handshake",
  "hatching-chick",
  "headphone",
  "herb",
  "hibiscus",
  "hiking-boot",
  "honeybee",
  "hot-beverage",
  "hot-springs",
  "hourglass-not-done",
  "house",
  "house-with-garden",
  "key",
  "laptop",
  "lemon",
  "light-bulb",
  "lightning",
  "lotus",
  "magic-wand",
  "memo",
  "military-medal",
  "mobile-phone",
  "money-bag",
  "mountain",
  "musical-note",
  "nazar-amulet",
  "notebook",
  "open-book",
  "paintbrush",
  "party-popper",
  "peach",
  "pencil",
  "person-biking",
  "person-in-lotus-position",
  "person-lifting-weights",
  "person-running",
  "person-swimming",
  "person-walking",
  "pig-face",
  "pizza",
  "potted-plant",
  "prayer-beads",
  "pulse",
  "puzzle-piece",
  "rabbit-face",
  "rainbow",
  "receipt",
  "red-apple",
  "red-heart",
  "ringed-planet",
  "rocket",
  "ruler",
  "running-shoe",
  "scale",
  "seedling",
  "shield",
  "shopping-bags",
  "shopping-cart",
  "shower",
  "snowflake",
  "soap",
  "soccer-ball",
  "sparkles",
  "sparkling-heart",
  "sponge",
  "sports-medal",
  "star",
  "strawberry",
  "sun",
  "sunflower",
  "sunrise",
  "teacup-without-handle",
  "tennis",
  "thermometer",
  "timer",
  "toothbrush",
  "train",
  "trophy",
  "tropical-drink",
  "tulip",
  "turtle",
  "umbrella",
  "water-wave",
  "whale",
  "wine-glass",
  "woman-in-lotus-position",
  "wrapped-gift",
] as const;

export type IconKey = (typeof ICON_KEYS)[number];

export const ICON_GROUPS: ReadonlyArray<{ readonly label: string; readonly keys: readonly IconKey[] }> = [
  { label: "Nature", keys: ["sun", "crescent-moon", "sunrise", "rainbow", "cloud", "umbrella", "snowflake", "droplet", "water-wave", "seedling", "herb", "four-leaf-clover", "potted-plant", "sunflower", "cherry-blossom", "tulip", "hibiscus", "lotus", "fallen-leaf", "evergreen-tree", "mountain", "camping", "beach-with-umbrella", "ringed-planet", "comet", "hot-springs"] },
  { label: "Creatures", keys: ["butterfly", "honeybee", "dog-face", "cat-face", "rabbit-face", "bird", "hatching-chick", "turtle", "whale", "pig-face"] },
  { label: "Food", keys: ["hot-beverage", "teacup-without-handle", "glass-of-milk", "red-apple", "green-apple", "banana", "avocado", "broccoli", "carrot", "bread", "bowl-with-spoon", "green-salad", "fork-and-knife-with-plate", "pizza", "birthday-cake", "cookie", "lemon", "grapes", "strawberry", "peach", "cheese-wedge", "egg", "wine-glass", "beer-mug", "bottle-with-popping-cork", "tropical-drink"] },
  { label: "Body & mind", keys: ["flexed-biceps", "running-shoe", "bicycle", "soccer-ball", "basketball", "tennis", "person-in-lotus-position", "woman-in-lotus-position", "person-running", "person-biking", "person-lifting-weights", "person-swimming", "person-walking", "brain", "anatomical-heart", "red-heart", "sparkling-heart", "bed", "alarm-clock", "hourglass-not-done", "candle", "prayer-beads", "nazar-amulet"] },
  { label: "Home", keys: ["house", "house-with-garden", "bubbles", "soap", "toothbrush", "shower", "bathtub", "broom", "sponge", "shopping-cart", "shopping-bags", "key", "envelope", "light-bulb", "calendar"] },
  { label: "Learn & create", keys: ["books", "open-book", "notebook", "memo", "pencil", "paintbrush", "artist-palette", "musical-note", "guitar", "headphone", "laptop", "desktop-computer", "mobile-phone", "puzzle-piece", "compass", "magic-wand", "crystal-ball", "bullseye"] },
  { label: "Measure", keys: ["gauge", "scale", "ruler", "thermometer", "pulse", "footprints", "timer", "lightning", "bed", "droplet", "anatomical-heart", "chart-increasing", "chart-decreasing"] },
  { label: "Money", keys: ["money-bag", "coin", "dollar-banknote", "euro-banknote", "credit-card", "bank", "receipt", "chart-increasing", "chart-decreasing", "bar-chart", "shield", "gem-stone"] },
  { label: "Travel", keys: ["automobile", "bus", "airplane", "fuel-pump", "train", "hiking-boot", "rocket"] },
  { label: "Celebrate", keys: ["sparkles", "star", "glowing-star", "fire", "party-popper", "balloon", "confetti-ball", "wrapped-gift", "crown", "trophy", "1st-place-medal", "2nd-place-medal", "3rd-place-medal", "sports-medal", "military-medal", "handshake"] },
];

export const DEFAULT_ROUTINE_ICON: IconKey = "sunrise";
export const DEFAULT_HABIT_ICON: IconKey = "seedling";
export const DEFAULT_ACCOUNT_ICON: IconKey = "bank";
export const DEFAULT_CATEGORY_ICON: IconKey = "receipt";
export const DEFAULT_GOAL_ICON: IconKey = "money-bag";
export const DEFAULT_MEASURE_ICON: IconKey = "gauge";

export const MEDAL_LABELS: Record<MedalKind, { readonly title: string; readonly description: string }> = {
  "first-step": { title: "First step", description: "The first time you showed up." },
  "streak-7": { title: "One week", description: "A week without missing." },
  "streak-30": { title: "One month", description: "A month without missing." },
  "streak-100": { title: "Hundred", description: "A hundred days without missing." },
  "streak-365": { title: "A whole year", description: "A whole year without missing." },
  "perfect-week": { title: "Perfect week", description: "Every habit, every scheduled day of the week." },
  "perfect-month": { title: "Perfect month", description: "Every habit, every scheduled day of the month." },
  "routine-week": { title: "Routine week", description: "A routine completed on every scheduled day for a week." },
  "routine-month": { title: "Routine month", description: "A routine completed on every scheduled day for a month." },
  saver: { title: "Saver", description: "A savings goal reached." },
  "budget-keeper": { title: "Budget keeper", description: "A month closed with every budget respected." },
};
